defaults: &defaults
  working_directory: ~/openfisca-rennesmetropole
  docker:
    - image: python:3.6.7

upgrade_pip: &upgrade_pip
  run:
    name: Upgrade pip
    command: pip install --upgrade pip wheel

install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: pip install . --upgrade && pip install ".[test]"

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *upgrade_pip
      - *install_dependencies
      - run:
          name: Run unit tests
          command: openfisca-run-test tests/**/*.yaml --extensions openfisca_rennesmetropole

workflows:
  version: 2
  test:
    jobs:
      - test
